import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

from app.domain.phase2 import CadGenerationRequest
from app.repositories.artifacts import ArtifactRepository


def _layout(request: CadGenerationRequest) -> dict[str, float | int]:
    design = request.design
    occupied = design.fin_count * design.fin_thickness + (design.fin_count - 1) * design.fin_spacing
    width = request.base_width or max(120.0, occupied + request.edge_margin * 2)
    if occupied + request.edge_margin * 2 > width + 1e-9:
        raise ValueError("Fins do not fit within base_width and edge margins")
    first_y = (width - occupied) / 2
    return {
        "base_length": request.base_length,
        "base_width": round(width, 6),
        "base_thickness": request.base_thickness,
        "fin_count": design.fin_count,
        "fin_thickness": design.fin_thickness,
        "fin_height": design.fin_height,
        "fin_spacing": design.fin_spacing,
        "first_fin_y": round(first_y, 6),
    }


def _freecad_script(cad_id: str, geometry: dict[str, float | int]) -> str:
    return f'''# Generated by Thermoform. Execute with: FreeCADCmd {cad_id}.py [output-directory]
import sys
from pathlib import Path

import FreeCAD as App
import Mesh
import Part

OUTPUT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent
OUTPUT.mkdir(parents=True, exist_ok=True)
doc = App.newDocument("{cad_id}")

shape = Part.makeBox({geometry["base_length"]}, {geometry["base_width"]}, {geometry["base_thickness"]})
for index in range({geometry["fin_count"]}):
    y = {geometry["first_fin_y"]} + index * ({geometry["fin_thickness"]} + {geometry["fin_spacing"]})
    fin = Part.makeBox(
        {geometry["base_length"]},
        {geometry["fin_thickness"]},
        {geometry["fin_height"]},
        App.Vector(0, y, {geometry["base_thickness"]}),
    )
    shape = shape.fuse(fin)

part = doc.addObject("PartDesign::Feature", "HeatSink")
part.Label = "Thermoform optimized heat sink"
part.Shape = shape
doc.recompute()
Part.export([part], str(OUTPUT / "{cad_id}.step"))
Mesh.export([part], str(OUTPUT / "{cad_id}.stl"))
doc.saveAs(str(OUTPUT / "{cad_id}.FCStd"))
'''


def _normal(a, b, c) -> tuple[float, float, float]:
    ux, uy, uz = (b[index] - a[index] for index in range(3))
    vx, vy, vz = (c[index] - a[index] for index in range(3))
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    length = max((nx * nx + ny * ny + nz * nz) ** 0.5, 1e-12)
    return nx / length, ny / length, nz / length


def _box_triangles(x0, y0, z0, dx, dy, dz):
    vertices = [
        (x0, y0, z0), (x0 + dx, y0, z0), (x0 + dx, y0 + dy, z0), (x0, y0 + dy, z0),
        (x0, y0, z0 + dz), (x0 + dx, y0, z0 + dz),
        (x0 + dx, y0 + dy, z0 + dz), (x0, y0 + dy, z0 + dz),
    ]
    faces = [
        (0, 2, 1), (0, 3, 2), (4, 5, 6), (4, 6, 7),
        (0, 1, 5), (0, 5, 4), (1, 2, 6), (1, 6, 5),
        (2, 3, 7), (2, 7, 6), (3, 0, 4), (3, 4, 7),
    ]
    return [(vertices[a], vertices[b], vertices[c]) for a, b, c in faces]


def _fallback_stl(cad_id: str, geometry: dict[str, float | int]) -> str:
    triangles = _box_triangles(
        0, 0, 0, geometry["base_length"], geometry["base_width"], geometry["base_thickness"]
    )
    for index in range(int(geometry["fin_count"])):
        y = geometry["first_fin_y"] + index * (geometry["fin_thickness"] + geometry["fin_spacing"])
        triangles.extend(
            _box_triangles(
                0,
                y,
                geometry["base_thickness"],
                geometry["base_length"],
                geometry["fin_thickness"],
                geometry["fin_height"],
            )
        )
    lines = [f"solid {cad_id}"]
    for a, b, c in triangles:
        nx, ny, nz = _normal(a, b, c)
        lines.extend(
            [
                f"  facet normal {nx:.8g} {ny:.8g} {nz:.8g}",
                "    outer loop",
                *(f"      vertex {point[0]:.8g} {point[1]:.8g} {point[2]:.8g}" for point in (a, b, c)),
                "    endloop",
                "  endfacet",
            ]
        )
    lines.append(f"endsolid {cad_id}")
    return "\n".join(lines) + "\n"


def generate_cad(
    request: CadGenerationRequest, repository: ArtifactRepository | None = None
) -> dict[str, Any]:
    repository = repository or ArtifactRepository()
    geometry = _layout(request)
    fingerprint = {"geometry": geometry, "material": request.material, "schema": "freecad-v1"}
    cad_id = repository.version(fingerprint, "cad")
    script_name = f"{cad_id}.py"
    stl_name = f"{cad_id}.stl"
    step_name = f"{cad_id}.step"
    script_path = repository.save_cad_artifact(cad_id, script_name, _freecad_script(cad_id, geometry))

    freecad_command = shutil.which("FreeCADCmd") or shutil.which("freecadcmd")
    freecad_error = None
    if freecad_command:
        try:
            subprocess.run(
                [freecad_command, str(script_path), str(script_path.parent)],
                check=True,
                capture_output=True,
                text=True,
                timeout=120,
            )
        except (subprocess.SubprocessError, OSError) as exc:
            freecad_error = str(exc)

    stl_path = script_path.parent / stl_name
    step_path = script_path.parent / step_name
    fallback_used = not stl_path.exists()
    if fallback_used:
        repository.save_cad_artifact(cad_id, stl_name, _fallback_stl(cad_id, geometry))

    volume_mm3 = (
        geometry["base_length"] * geometry["base_width"] * geometry["base_thickness"]
        + geometry["fin_count"]
        * geometry["base_length"]
        * geometry["fin_thickness"]
        * geometry["fin_height"]
    )
    metadata = {
        "cad_id": cad_id,
        "geometry": geometry,
        "material": request.material,
        "base_width_auto_sized": request.base_width is None,
        "cad_mass_estimate_g": round(float(volume_mm3) * 0.0027, 3),
        "freecad_available": bool(freecad_command),
        "freecad_executed": bool(freecad_command and not freecad_error),
        "freecad_error": freecad_error,
        "step_generated": step_path.exists(),
        "stl_generated": True,
        "stl_generator": "fallback_parametric_mesh" if fallback_used else "FreeCAD",
        "not_cfd_or_cae": True,
        "downloads": {
            "freecad_script": f"/api/v1/cad/{cad_id}/artifacts/{script_name}",
            "stl": f"/api/v1/cad/{cad_id}/artifacts/{stl_name}",
            "step": f"/api/v1/cad/{cad_id}/artifacts/{step_name}" if step_path.exists() else None,
        },
    }
    repository.save_cad_artifact(cad_id, "metadata.json", json.dumps(metadata, indent=2, sort_keys=True))
    return metadata
