apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: thanos-receive-object-store
  namespace: thermoform-observability
spec:
  provider: openbao
  parameters:
    roleName: thanos-receive
    audience: openbao
    objects: |
      - objectName: object-store.yml
        secretPath: kv/data/thanos/receive
        secretKey: object-store.yml
        filePermission: 0400
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: thanos-store-object-store
  namespace: thermoform-observability
spec:
  provider: openbao
  parameters:
    roleName: thanos-store
    audience: openbao
    objects: |
      - objectName: object-store.yml
        secretPath: kv/data/thanos/store
        secretKey: object-store.yml
        filePermission: 0400
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: thanos-compact-object-store
  namespace: thermoform-observability
spec:
  provider: openbao
  parameters:
    roleName: thanos-compact
    audience: openbao
    objects: |
      - objectName: object-store.yml
        secretPath: kv/data/thanos/compact
        secretKey: object-store.yml
        filePermission: 0400
