"use client";

import { useState } from "react";

const nav = [
  ["overview", "⌂", "Overview"], ["design", "◇", "Design Space"], ["doe", "▦", "DOE"],
  ["simulation", "ϟ", "Simulation"], ["analysis", "⌁", "Analysis"],
  ["surrogate", "⌘", "Surrogate Models"], ["optimization", "◎", "Optimization"],
  ["digital-twin", "◫", "Digital Twin"], ["cad", "⬡", "CAD"],
];

const stages = [
  ["01", "Design space", "5 variables", "done"], ["02", "DOE", "64 experiments", "done"],
  ["03", "Simulation", "64 / 64 complete", "done"], ["04", "Surrogate", "GPR selected", "active"],
  ["05", "Optimization", "Ready to run", "next"],
];

function PageHead({kicker,title,description,badge}:{kicker:string,title:string,description:string,badge?:string}) {
  return <><div className="eyebrow">{kicker} <span>•</span> DATASET V12</div><div className="title-row"><div><h1>{title}</h1><p>{description}</p></div>{badge && <div className="status-pill"><span/> {badge}</div>}</div></>;
}

function Overview({go}:{go:(page:string)=>void}) {
  return <div className="content"><PageHead kicker="THERMAL DESIGN WORKSPACE" title="System overview" description="Monitor the engineering workflow from design space to optimized geometry." badge="Workflow healthy"/>
    <div className="metrics"><article><small>EXPERIMENTS</small><strong>64</strong><p><span className="up">↗ 12</span> since last run</p><i>▦</i></article><article><small>BEST MODEL</small><strong>GPR</strong><p><span>R² 0.984</span> · CV RMSE 1.21°C</p><i>⌘</i></article><article><small>BEST T<sub>MAX</sub></small><strong>68.4<em>°C</em></strong><p><span className="down">↓ 8.2°C</span> vs. baseline</p><i>ϟ</i></article><article><small>EST. MASS</small><strong>287<em>g</em></strong><p><span className="down">↓ 13%</span> vs. baseline</p><i>⬡</i></article></div>
    <section className="workflow-card"><div className="card-heading"><div><h2>Engineering workflow</h2><p>Current project progression and traceability</p></div><button onClick={()=>go("simulation")}>View activity log ↗</button></div><div className="pipeline">{stages.map(([num,name,detail,state],index)=><div className={`stage ${state}`} key={name}><div className="stage-top"><span>{num}</span>{state === "done"?<b>✓</b>:state === "active"?<b>◌</b>:<b>•</b>}</div><strong>{name}</strong><small>{detail}</small>{index<stages.length-1&&<i/>}</div>)}</div></section>
    <div className="lower-grid"><section className="performance-card"><div className="card-heading"><div><h2>Model performance</h2><p>Cross-validated RMSE by surrogate</p></div><div className="legend"><span/> RMSE (°C)</div></div><div className="chart"><div className="axis"><span>4</span><span>3</span><span>2</span><span>1</span><span>0</span></div><div className="bars">{[["RSM","3.48",87],["Random Forest","2.05",51],["XGBoost","1.62",40],["GPR","1.21",30]].map(([name,val,height])=><div className="bar-column" key={name}><div className={`bar ${name === "GPR"?"best":""}`} style={{height:`${height}%`}}><b>{val}</b></div><span>{name}</span></div>)}</div></div></section><section className="design-card"><div className="card-heading"><div><h2>Recommended design</h2><p>Lowest feasible thermal resistance</p></div><span className="candidate">CANDIDATE 07</span></div><div className="mini-design"><HeatSink/><div><small>T<sub>MAX</sub></small><strong>68.4°C</strong><small>R<sub>θ</sub></small><strong>0.434 K/W</strong></div></div><div className="parameters"><span><small>FINS</small><b>48</b></span><span><small>HEIGHT</small><b>52 mm</b></span><span><small>SPACING</small><b>2.4 mm</b></span><span><small>VELOCITY</small><b>3.2 m/s</b></span></div><button className="outline-button" onClick={()=>go("digital-twin")}>Inspect design <span>→</span></button></section></div>
  </div>;
}

function HeatSink({count=10}:{count?:number}) { return <div className="sink" aria-label="Parametric heat sink preview">{Array.from({length:Math.min(count,14)}).map((_,i)=><i key={i}/>)}</div>; }

function ModuleView({active,notify}:{active:string,notify:(s:string)=>void}) {
  const [method,setMethod]=useState("LHS"); const [runs,setRuns]=useState(64); const [fins,setFins]=useState(48); const [height,setHeight]=useState(52); const [spacing,setSpacing]=useState(2.4); const [velocity,setVelocity]=useState(3.2); const [model,setModel]=useState("GPR");
  const temp=(91.6-fins*.16-height*.11-spacing*.7-velocity*2.1).toFixed(1); const mass=Math.round(126+fins*2.25+height*.68); const theta=((Number(temp)-25)/100).toFixed(3);
  if(active==="design") return <div className="content"><PageHead kicker="PARAMETER SPACE" title="Design space" description="Define the geometry and operating bounds explored by the DOE engine." badge="Bounds valid"/><div className="module-grid"><section className="panel"><div className="panel-title"><div><h2>Design parameters</h2><p>Continuous values are normalized before sampling.</p></div><span className="tag">5 ACTIVE</span></div>{[["Fin count",fins,20,60,1,setFins,""],["Fin height",height,20,60,1,setHeight,"mm"],["Fin spacing",spacing,1,4,.1,setSpacing,"mm"],["Air velocity",velocity,.5,5,.1,setVelocity,"m/s"]].map(([label,value,min,max,step,setter,unit])=><label className="range-row" key={String(label)}><span><b>{label}</b><small>{min} — {max} {unit}</small></span><input type="range" min={Number(min)} max={Number(max)} step={Number(step)} value={Number(value)} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))}/><output>{value} {unit}</output></label>)}<label className="range-row fixed"><span><b>Fin thickness</b><small>0.3 — 1.0 mm</small></span><input type="range" min=".3" max="1" step=".1" defaultValue=".65"/><output>0.65 mm</output></label><button className="primary-action" onClick={()=>notify("Design space saved as version 13")}>Save design space <span>→</span></button></section><section className="panel preview-panel"><div className="panel-title"><div><h2>Parametric preview</h2><p>Geometry representation · not CFD</p></div><span className="candidate">LIVE</span></div><div className="large-sink"><HeatSink count={fins/4}/><div className="dimension horizontal">120 mm</div><div className="dimension vertical">{height} mm</div></div><div className="preview-stats"><span><small>EST. MASS</small><b>{mass} g</b></span><span><small>FIN AREA</small><b>{(fins*height*.024).toFixed(2)} m²</b></span><span><small>OPEN RATIO</small><b>{Math.round(spacing/(spacing+.65)*100)}%</b></span></div></section></div></div>;
  if(active==="doe") return <div className="content"><PageHead kicker="DESIGN OF EXPERIMENTS" title="Experiment matrix" description="Generate a space-filling, reproducible set of thermal design candidates." badge="Seed 42"/><section className="panel toolbar-panel"><div className="method-tabs">{["CCD","BBD","LHS"].map(x=><button className={method===x?"selected":""} onClick={()=>setMethod(x)} key={x}>{x}<small>{x==="CCD"?"Response surface":x==="BBD"?"Efficient quadratic":"Space filling"}</small></button>)}</div><label className="run-count">RUNS <input type="number" min="30" max="100" value={runs} onChange={e=>setRuns(Number(e.target.value))}/></label><button className="primary-action compact" onClick={()=>notify(`${method} matrix generated · ${runs} runs · seed 42`)}>Generate matrix</button></section><section className="panel table-panel"><div className="panel-title"><div><h2>{method} experiment matrix</h2><p>{runs} runs · 5 factors · maximin criterion · seed 42</p></div><button className="text-button">Export CSV ↓</button></div><div className="data-table"><div className="tr head"><span>RUN</span><span>FIN COUNT</span><span>THICKNESS</span><span>HEIGHT</span><span>SPACING</span><span>VELOCITY</span><span>STATUS</span></div>{[[1,30,.40,30,1.5,1.0],[2,40,.50,40,2.0,2.0],[3,50,.70,50,2.5,3.0],[4,45,.60,55,2.8,3.6],[5,36,.85,34,3.3,4.2],[6,58,.35,48,1.8,2.7]].map((r,i)=><div className="tr" key={i}>{r.map((x,j)=><span key={j}>{x}{j>1&&j<5?" mm":j===5?" m/s":""}</span>)}<span className="ready">● READY</span></div>)}</div><div className="table-foot">Showing 6 of {runs} experiments <span>Version will be frozen on simulation</span></div></section></div>;
  if(active==="simulation") return <div className="content"><PageHead kicker="PHYSICS ENGINE" title="Batch simulation" description="Evaluate heat transfer, pressure drop, and mass with the deterministic reduced-order model." badge="64 / 64 complete"/><div className="metrics compact-metrics"><article><small>MEDIAN T<sub>MAX</sub></small><strong>74.8<em>°C</em></strong><p>Range 66.9 — 91.2</p></article><article><small>AVG. R<sub>θ</sub></small><strong>0.498<em>K/W</em></strong><p>Power 100 W</p></article><article><small>AVG. ΔP</small><strong>18.6<em>Pa</em></strong><p>Limit 35 Pa</p></article><article><small>RUNTIME</small><strong>3.8<em>s</em></strong><p>Seed 42 · deterministic</p></article></div><section className="panel"><div className="panel-title"><div><h2>Simulation runs</h2><p>Physics simulator v1.4.2 · dataset v12</p></div><button className="primary-action compact" onClick={()=>notify("Re-run queued with the same deterministic seed")}>Re-run batch</button></div><div className="run-list">{[["EXP-064","68.4°C","0.434 K/W","22.1 Pa","287 g"],["EXP-063","71.2°C","0.462 K/W","16.8 Pa","301 g"],["EXP-062","69.7°C","0.447 K/W","27.4 Pa","274 g"],["EXP-061","76.1°C","0.511 K/W","12.3 Pa","264 g"],["EXP-060","72.8°C","0.478 K/W","19.5 Pa","293 g"]].map((r,i)=><div className="run-row" key={r[0]}><span className="run-id"><i>✓</i><b>{r[0]}</b><small>completed · {(1.8+i*.4).toFixed(1)} ms</small></span>{r.slice(1).map((x,j)=><span key={j}><small>{["TMAX","Rθ","ΔP","MASS"][j]}</small><b>{x}</b></span>)}<button>›</button></div>)}</div></section></div>;
  if(active==="analysis") return <div className="content"><PageHead kicker="STATISTICAL ANALYSIS" title="Effects & diagnostics" description="Understand which factors and interactions control maximum temperature." badge="ANOVA significant"/><div className="analysis-grid"><section className="panel"><div className="panel-title"><div><h2>Standardized effects</h2><p>Response: T<sub>max</sub> · α = 0.05</p></div><span className="tag">MAIN EFFECTS</span></div><div className="effects">{[["Air velocity",94,"−18.42"],["Fin height",67,"−11.07"],["Fin count",54,"−8.91"],["Spacing × Velocity",39,"−5.62"],["Fin spacing",31,"−4.08"],["Thickness",18,"−2.11"]].map(([n,w,v])=><div key={n}><span>{n}</span><i><b style={{width:`${w}%`}}/></i><em>{v}</em></div>)}</div></section><section className="panel"><div className="panel-title"><div><h2>Residual vs fitted</h2><p>Model residual diagnostics</p></div><span className="candidate">PASS</span></div><div className="scatter"><i className="zero"/>{Array.from({length:28}).map((_,i)=><b key={i} style={{left:`${7+(i*31)%87}%`,top:`${15+(i*47)%69}%`}}/>)}</div><div className="diagnostic-stats"><span><small>SHAPIRO-WILK</small><b>p = 0.218</b></span><span><small>OUTLIERS</small><b>1 flagged</b></span><span><small>BIAS</small><b>−0.03°C</b></span></div></section><section className="panel wide"><div className="panel-title"><div><h2>ANOVA</h2><p>Quadratic response surface · 95% confidence</p></div><button className="text-button">Full report ↓</button></div><div className="anova"><div className="tr head"><span>SOURCE</span><span>SUM SQ.</span><span>DF</span><span>MEAN SQ.</span><span>F-VALUE</span><span>P-VALUE</span></div>{[["Model","1,284.2","20","64.21","38.47","< 0.001"],["Linear","1,021.8","5","204.36","122.39","< 0.001"],["Interactions","188.6","10","18.86","11.29","0.002"],["Quadratic","73.8","5","14.76","8.84","0.008"],["Residual","71.8","43","1.67","—","—"]].map(r=><div className="tr" key={r[0]}>{r.map((x,i)=><span className={i===5&&x.includes("<")?"significant":""} key={i}>{x}</span>)}</div>)}</div></section></div></div>;
  if(active==="surrogate") return <div className="content"><PageHead kicker="SURROGATE MODELING" title="Model comparison" description="Select the best generalizing predictor—not simply the highest training score." badge="GPR recommended"/><section className="panel"><div className="model-table"><div className="tr head"><span>MODEL</span><span>R² TEST</span><span>RMSE</span><span>MAE</span><span>CV RMSE</span><span>TRAINING</span><span>STATUS</span></div>{[["RSM","0.921","3.48°C","2.61°C","3.72°C","18 ms"],["Random Forest","0.963","2.05°C","1.48°C","2.22°C","146 ms"],["XGBoost","0.976","1.62°C","1.19°C","1.78°C","204 ms"],["GPR","0.984","1.21°C","0.92°C","1.34°C","312 ms"]].map(r=><button className={`tr ${model===r[0]?"model-selected":""}`} onClick={()=>setModel(r[0])} key={r[0]}>{r.map((x,i)=><span key={i}>{i===0&&<i className="radio"/>}{x}</span>)}<span>{r[0]==="GPR"?<b className="recommended">RECOMMENDED</b>:"Trained"}</span></button>)}</div></section><div className="module-grid top-gap"><section className="panel"><div className="panel-title"><div><h2>{model} prediction</h2><p>Candidate 07 · dataset v12</p></div><span className="tag">LIVE</span></div><div className="prediction"><div><small>PREDICTED T<sub>MAX</sub></small><strong>{model==="GPR"?"68.4":"69.1"}<em>°C</em></strong><p>95% confidence: 66.1 — 70.7°C</p></div><div className="gauge"><i style={{width:"64%"}}/><b>80°C LIMIT</b></div></div></section><section className="panel"><div className="panel-title"><div><h2>Uncertainty</h2><p>Predictive σ across design space</p></div></div><div className="uncertainty"><strong>± 2.3°C</strong><div>{Array.from({length:18}).map((_,i)=><i key={i} style={{height:`${25+(i*29)%62}%`}}/>)}</div><p>Low uncertainty around sampled regions. Highest near boundary combinations.</p></div></section></div></div>;
  if(active==="optimization") return <div className="content"><PageHead kicker="MULTI-OBJECTIVE SEARCH" title="Optimization" description="Explore feasible trade-offs between thermal performance, pressure drop, and mass." badge="128 generations"/><div className="optimization-layout"><section className="panel objective-panel"><div className="panel-title"><div><h2>Objectives</h2><p>NSGA-II configuration</p></div></div>{[["Tmax","Minimize","°C"],["Pressure drop","Minimize","Pa"],["Mass","Minimize","g"]].map(r=><div className="objective" key={r[0]}><i>↓</i><span><b>{r[0]}</b><small>{r[1]}</small></span><em>{r[2]}</em></div>)}<h3>CONSTRAINTS</h3><div className="constraint"><span>T<sub>MAX</sub></span><b>&lt; 80°C</b></div><div className="constraint"><span>Pressure drop</span><b>&lt; 35 Pa</b></div><button className="primary-action" onClick={()=>notify("Optimization run started · 128 generations")}>Run optimization <span>→</span></button></section><section className="panel pareto-panel"><div className="panel-title"><div><h2>Pareto front</h2><p>Temperature vs. mass · color = pressure drop</p></div><div className="legend gradient">LOW ΔP <i/> HIGH ΔP</div></div><div className="pareto"><span className="ylabel">T<sub>MAX</sub> (°C)</span><i className="front-line"/>{[[11,20],[19,31],[29,40],[39,49],[50,57],[61,63],[72,70],[84,76]].map((p,i)=><button key={i} className={i===3?"chosen":""} style={{left:`${p[0]}%`,top:`${p[1]}%`}} onClick={()=>notify(`Candidate ${String(i+1).padStart(2,"0")} selected`)} aria-label={`Select candidate ${i+1}`}/>) }<b className="xlabel">MASS (g)</b></div></section></div><div className="candidate-strip">{[["01","66.9°C","341 g","31.2 Pa"],["04","68.4°C","287 g","22.1 Pa"],["07","71.0°C","248 g","16.8 Pa"]].map((r,i)=><button className={i===1?"selected":""} key={r[0]}><small>CANDIDATE {r[0]}</small><strong>{r[1]}</strong><span>{r[2]} · {r[3]}</span></button>)}</div></div>;
  if(active==="digital-twin") return <div className="content"><PageHead kicker="INTERACTIVE PREDICTION" title="Digital twin" description="Explore design changes instantly with the GPR surrogate and quantified uncertainty." badge="Model v8 · live"/><div className="twin-layout"><section className="panel twin-controls"><div className="panel-title"><div><h2>What-if controls</h2><p>Predictions update without rerunning simulation.</p></div><button className="text-button" onClick={()=>{setFins(48);setHeight(52);setSpacing(2.4);setVelocity(3.2)}}>Reset</button></div>{[["Fin count",fins,20,60,1,setFins,""],["Fin height",height,20,60,1,setHeight,"mm"],["Fin spacing",spacing,1,4,.1,setSpacing,"mm"],["Air velocity",velocity,.5,5,.1,setVelocity,"m/s"]].map(([label,value,min,max,step,setter,unit])=><label className="range-row" key={String(label)}><span><b>{label}</b><small>{min} — {max} {unit}</small></span><input type="range" min={Number(min)} max={Number(max)} step={Number(step)} value={Number(value)} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))}/><output>{value} {unit}</output></label>)}</section><section className="panel twin-surface"><div className="panel-title"><div><h2>Response surface</h2><p>Fin height × air velocity → T<sub>max</sub></p></div><span className="candidate">GPR μ(x)</span></div><div className="surface"><div className="contours">{Array.from({length:7}).map((_,i)=><i key={i}/>)}</div><span className="current" style={{left:`${25+velocity*9}%`,top:`${78-height}%`}}>●<b>CURRENT</b></span><span className="optimal">★<b>OPTIMAL</b></span></div></section><aside className="twin-results"><article><small>PREDICTED T<sub>MAX</sub></small><strong>{temp}<em>°C</em></strong><p className={Number(temp)<80?"pass":"fail"}>{Number(temp)<80?"✓ Within constraint":"× Above constraint"}</p></article><article><small>THERMAL RESISTANCE</small><strong>{theta}<em>K/W</em></strong><p>± 0.023 uncertainty</p></article><article><small>PRESSURE DROP</small><strong>{(4.8+velocity*4.9/spacing).toFixed(1)}<em>Pa</em></strong><p>35 Pa limit</p></article><article><small>ESTIMATED MASS</small><strong>{mass}<em>g</em></strong><p>Al 6063-T5</p></article><button className="primary-action" onClick={()=>notify("Current point saved as Candidate 12")}>Save candidate</button></aside></div></div>;
  return <div className="content"><PageHead kicker="PARAMETRIC GEOMETRY" title="CAD generation" description="Turn an optimized parameter set into a traceable manufacturing-ready artifact." badge="Geometry valid"/><div className="cad-layout"><section className="panel cad-preview"><div className="panel-title"><div><h2>Optimal heat sink</h2><p>Candidate 07 · isometric preview</p></div><span className="tag">SOLID</span></div><div className="cad-stage"><div className="cad-sink"><HeatSink count={12}/><i className="base"/></div><span className="axis x">X</span><span className="axis y">Y</span><span className="axis z">Z</span></div><div className="viewer-tools"><button>＋</button><button>−</button><button>⌂</button><span>Perspective · shaded edges</span></div></section><section className="panel cad-meta"><div className="panel-title"><div><h2>Geometry specification</h2><p>FreeCAD adapter · schema v2</p></div></div>{[["Fin count","48"],["Fin thickness","0.65 mm"],["Fin height","52.0 mm"],["Fin spacing","2.40 mm"],["Base plate","120 × 90 × 5 mm"],["Material","Al 6063-T5"]].map(r=><div className="spec" key={r[0]}><span>{r[0]}</span><b>{r[1]}</b></div>)}<div className="artifact"><span>ARTIFACT ID</span><code>cad_01J8K4F2_v003</code><small>SHA-256 verified · model v8 · dataset v12</small></div><button className="primary-action" onClick={()=>notify("STEP package generated and verified")}>Generate STEP <span>↓</span></button><button className="outline-button" onClick={()=>notify("STL mesh generated")}>Export STL <span>↓</span></button><p className="disclaimer">Geometry preview only. Manufacturing tolerances require downstream CAD validation.</p></section></div></div>;
}

export default function Home() {
  const [active, setActive] = useState("overview");
  const [toast,setToast]=useState("");
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  return (
    <main className="shell">
      <aside className="sidebar">
        <div className="brand"><span className="brandmark">◒</span><div><strong>THERMOFORM</strong><small>Engineering Intelligence</small></div></div>
        <nav aria-label="Primary navigation">
          {nav.map(([id, icon, label]) => <button key={id} className={active === id ? "nav-active" : ""} onClick={() => setActive(id)}><span>{icon}</span>{label}{id === "simulation" && <i>64</i>}</button>)}
        </nav>
        <div className="sidebar-bottom">
          <div className="system"><span className="pulse"/><div><strong>All systems nominal</strong><small>Physics engine v1.4.2</small></div></div>
          <button className="avatar"><span>HY</span><div><strong>Huang Yanwei</strong><small>Thermal Engineer</small></div><b>•••</b></button>
        </div>
      </aside>
      <section className="workspace">
        <header>
          <div className="project-select"><small>PROJECT</small><button>CPU-AX91 / Passive Cooling <span>⌄</span></button></div>
          <div className="header-actions"><button className="icon-button" aria-label="Search">⌕</button><button className="icon-button" aria-label="Notifications">♢<i/></button><button className="run-button" onClick={()=>notify("Workflow queued · DOE → simulation → training")}>Run workflow <span>→</span></button></div>
        </header>
        {active==="overview"?<Overview go={setActive}/>:<ModuleView active={active} notify={notify}/>}
      </section>
      {toast&&<div className="toast"><i>✓</i>{toast}</div>}
    </main>
  );
}
