apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thermoform-observability
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configuration.yaml
  - services.yaml
  - receive.yaml
  - store.yaml
  - query.yaml
  - compact.yaml
  - pdb.yaml
  - networkpolicy.yaml
