apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: receive
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thanos-store
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: store
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: store
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thanos-query
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/component: query
