apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-receive
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-store
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: store
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-query
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-compact
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: compact
automountServiceAccountToken: true
