apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../observability
  - storageclass.yaml
patches:
  - target:
      version: v1
      kind: ServiceAccount
      name: thanos-receive
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/REPLACE_WITH_THANOS_RECEIVE_ROLE
          eks.amazonaws.com/sts-regional-endpoints: "true"
  - target:
      version: v1
      kind: ServiceAccount
      name: thanos-store
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/REPLACE_WITH_THANOS_STORE_ROLE
          eks.amazonaws.com/sts-regional-endpoints: "true"
  - target:
      version: v1
      kind: ServiceAccount
      name: thanos-compact
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/REPLACE_WITH_THANOS_COMPACT_ROLE
          eks.amazonaws.com/sts-regional-endpoints: "true"
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: thanos-receive
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: thermoform-ebs-gp3
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: thanos-compact
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: thermoform-ebs-gp3
